# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Product.create(name: "Thorlos Women's Socks", price: 13.99, image_path: "https://images-na.ssl-images-amazon.com/images/I/712sp%2BxSHvL._AC_UX679_.jpg", description:"Thorlo 84N provides ultimate in protection and performance with maximum padding in both the ball and heel strike zones")
Product.create(name: "Clever Coffee Maker With Bonus Filters Included - (Cloud)", price: 25.95, image_path: "https://images-na.ssl-images-amazon.com/images/I/81hWn5XYayL._AC_SL1500_.jpg", description:"INCLUDES 100 FILTERS! The Clever Coffee Dripper combines the best features of French Press and filter drip brewing, eliminating the drawbacks of each. By adding a stopper to a filtercone, the Clever Coffee Dripper combines control over steeping time with a sediment free cup.The dripper will fit on cups and thermoses with tops wider than 1.5 and less than 3.75 in diameter. Of course, if you put the dripper on a very narrow thermos you should make sure it is stable. Cleaning: Cleaning the Clever Coffee Dripper is ver easy. Just dispose of the used grounds and filter and rinse. Do not allow residue to build up in the filter. Lightly scrub the cone with very hot water and a sponge or brush, taking care to clean shut off mechanism lightly from the top. If necessary, use a detergent-free cleaner designed for carafes and filtercones.")
Product.create(name: "DjuiinoStar Low Temperature Stirling Engine", price: 49.99, image_path: "https://images-na.ssl-images-amazon.com/images/I/71ukU%2BIFkPL._AC_SL1500_.jpg", description:"This engine is driven by the temperature differential between the top and bottom plates. To create enough temperature differential, simply put it on a cup of hot water. The rotation speed depends on the temperature differential: the higher, the faster. When in good condition, that is, after working for a while and being lubricated, it can reach a speed around 220-250 RPM driven by boiling water. Please refer to the video attached to learn how to operate and lubricate.")
Product.create(name: "LEGO Ideas International Space Station 21321 Building Kit, Adult Set for Display, New 2020 (864 Pieces)", price: 69.99, image_path: "https://images-na.ssl-images-amazon.com/images/I/91g71Jc3KcL._AC_SL1500_.jpg", description:"Build and display this spectacular LEGO Ideas 21321 ISS (International Space Station). Packed with authentic ISS details, including a posable Canadarm2 and 2 rotating joints that coincide with 8 adjustable ‘solar panels’, this 864-piece set is a wonderful gift idea for space enthusiasts, adult LEGO fans or any experienced builder. This awesome LEGO spaceship model comes with a display stand, a buildable mini NASA space shuttle and 3 mini cargo spacecrafts, plus 2 astronaut microfigures to create a striking centerpiece in any room. Illustrated instructions are included, plus a 148-page booklet with fascinating ISS facts and information about the LEGO fan who created this space model kit and its LEGO designer. The infinitely diverse array of LEGO Ideas sets are all created by LEGO fans and voted for by LEGO fans. Inspired by real life, action heroes, iconic movies, popular TV series or totally original concepts, there is something to delight all ages.")
